### ISSUE TITLE
Several classes are shown in history progression graph

### ISSUE THREAD

**Issue by matletix** [TheSoftwareFactory/DlearnHelsinki#123]
On the teacher history page, for the progression graph, the surveys of other classes are shown on the progression curve of the students

**Comment by mjbehrens** [comment]
![image](https://user-images.githubusercontent.com/33420821/32891976-fa4338f6-cad4-11e7-879c-809db3800818.png)

In this class only 2 Surveys are open. But as you can see the Progression bar Shows 4.
