### ISSUE TITLE
New student form, age

### ISSUE THREAD

**Issue by Whippler** [TheSoftwareFactory/DlearnHelsinki#127]
Age should not be static. Should be given as a birth year/day

**Comment by mjbehrens** [comment]
-talked with Nicolas, problem is client doesn´t want to save the birthdate (too much Information)
-> Client issue

**Comment by esaaksvu** [comment]
We were thinking birth year, so it would be possible to calculate age according to it.
Like
> born in 2004, 2017-2004 = 13 years old
