### ISSUE TITLE
Frontend Create Student doesn't work on local backend

### ISSUE THREAD

**Issue by esaaksvu** [TheSoftwareFactory/DlearnHelsinki#128]
Create students through frontend fails with alert:
> Error while creating the account. Please check if this account does not already exist.

Network tab shows 
> 405 Method Not Allowed

Direct backend call "create_student" works fine.

> curl -H 'authorization: Basic dGVhY2hlcjox' -H 'content-type: application/json' --request PUT localhost:8080/webapi/teachers/4/create_student -d @data.json

I think error is in `src/components/teacherCompo/Group.js` file which uses POST instead of PUT, I'll continue investigating.

**Comment by Whippler** [comment]
Tried with Heroku backend, can't seem to add new or existing students to a group. Getting the same 405 error.

**Comment by esaaksvu** [comment]
I fixed issue in backend
