### ISSUE TITLE
Teacher dashboard doesn't show the last survey

### ISSUE THREAD

**Issue by matletix** [TheSoftwareFactory/DlearnHelsinki#144]
On the teacher dashboard, only the first survey ever opened is displayed. When the teacher open and closes new surveys, the overview of the last closed survey should be displayed in its dashboard.

**Comment by esaaksvu** [comment]
Could this be caused by backend?

**Comment by matletix** [comment]
Yeah it could, because I think it was working fine before, @alkalinan any thoughts ?

**Comment by alkalinan** [comment]
@matletix, can you send pictures ? Also it would be interesting to check the content of the database and see if those survey are really opened

**Comment by matletix** [comment]
@alkalinan For the English Class 2018, 3 surveys have been opened and closed, the first being Vocabulary 2
![screenshot-2017-11-20 dlearn app 1](https://user-images.githubusercontent.com/19894690/33019779-7408dbb4-ce04-11e7-8202-8ef637939ab2.png)
The last one, aka Grammar, should be displayed on the teacher dashboard, but it's still Vocabulary 2 that is shown.
![screenshot-2017-11-20 dlearn app 2](https://user-images.githubusercontent.com/19894690/33019836-a75ac04a-ce04-11e7-9615-d80968dad351.png)

**Comment by alkalinan** [comment]
Ok I will investigated this issue for tonight, thanks

**Comment by Auua** [comment]
Heh, If you change 
lastSurvey = surveys.filter(function (s) {
          return s.end_date == last_d;
        })[0];
to 
lastSurvey = surveys.filter(function (s) {
          return s.end_date == last_d;
        })[1];
it gives the one survey before :D
