### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'i.title.toLowerCase')

### ISSUE THREAD

**Issue by alkalinan** [TheSoftwareFactory/DlearnHelsinki#49]
In History.js while search by name, the app crash if the name of the survey is undefined. 

```javascript
 52 | }
 52 | var queryResult = [];
 53 | tempData.forEach(function (i) {
 54 |     if ((i.title.toLowerCase().indexOf(queryText) != -1)
 55 |         || (i._id.toString().indexOf(queryText) != -1)
 56 |         || (i.start_date.indexOf(queryText) != -1)) {
 57 | 
```

**Comment by MarEf** [comment]
I was unable to replicate this error, nor create a situation where the name of a survey is undefined. Hasn't this bug been fixed by simply requiring that a survey must have a name?

**Comment by alkalinan** [comment]
If the problem only appear if a survey has no name. I have made a lot of security so it's normal that you cannot easly replicate the bug. However, I think, that because we cannot be sure that surveys will always have a name, we should fix that by having a check (if null then..)

**Comment by MarEf** [comment]
Hmm... I think there should be no reason why this bug would show itself in normal use. However, you're right that we should be prepared for it now that we know it's there. 

How about this: If the name (or date) is null, the survey will always be pushed to the search results. I can write the checks for that.

**Comment by alkalinan** [comment]
Sure, why not. As long as the app does not crash it's ok

**Comment by MarEf** [comment]
Checks have been added and the pull request has passed the test. I don't feel comfortable about merging stuff to master this close to the customer meeting, though, so it will be completed later today. Unless, of course, someone else wants to risk it.
