### ISSUE TITLE
Broken research bar in history

### ISSUE THREAD

**Issue by alkalinan** [TheSoftwareFactory/DlearnHelsinki#77]
For some reasons, the research cannot search with students and or groups in history.
It can do it only for Surveys.

**Comment by alkalinan** [comment]
in history :>  doSearch = function (queryText)

has to be adapt for student and groups

**Comment by matletix** [comment]
@alkalinan the history search bar seems to work well with students and groups. Is this fixed ?

**Comment by matletix** [comment]
Fixed
