### ISSUE TITLE
Bug in GraphRendererForSurveys

### ISSUE THREAD

**Issue by MarEf** [TheSoftwareFactory/DlearnHelsinki#82]
When going to the History-page, selecting a survey, and clicking on Class, the app will crash with a "TypeError: this.props.classes is undefined".

![screenshot from 2017-10-20 13-52-07](https://user-images.githubusercontent.com/3274160/31817848-60ebde1a-b59e-11e7-82f7-f457453a0d80.png)

**Comment by alkalinan** [comment]
issue fix in commit #84
